[package]
name = "adc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.4"
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
ic-cdk-timers = "0.1.1"
verity_dp_ic = { git = "https://github.com/usherlabs/ccamp.git", rev = "d0c4d619ae0896fc982ac69ea35b9014a19b2fe6"} # TODO: move this to the workspace file
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.4.3"
