[package]
name = "adc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.16"
ic-cdk-timers = "0.10" 
verity_dp_ic = { git = "https://github.com/usherlabs/ccamp.git", rev = "f8a9230c7dc2fac20604f4b7e3cf71a9f7e71e7f"} # TODO: move this to the workspace file
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.4.3"
