[workspace]
members = ["orchestrator", "processor/ic", "example_caller"]
resolver = "2"

[workspace.dependencies]
verity_dp_ic = { path = "./ccamp/ic/libraries" }
verity-client = { path = "./ccamp/rs/verity-client" }
