[workspace]
members = ["orchestrator", "processor/ic", "example_caller", "types"]
resolver = "2"

[workspace.dependencies]
verity_dp_ic = { version = "*" }
verity-client = { git = "git@github.com:usherlabs/verity-dp.git" }