[workspace]
members = ["orchestrator", "processor/ic"]
resolver = "2"

[workspace.dependencies]
verity_dp_ic = { path = "./ccamp/src/ic/libraries" }
verity-client = { path = "./ccamp/src/rs/verity-client" }
