[workspace]
members = ["orchestrator", "processor/ic", "example_caller", "types"]
resolver = "2"

[workspace.dependencies]
verity_dp_ic = { path = "./verity_dp/ic/libraries" }
verity-client = { path = "./verity_dp/rs/verity-client" }