services:
  # verity-prover:
  #   network_mode: "host"
  #   build:
  #     context: .prover
  #     dockerfile: prover.Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "8000:8000"
  
  orchestrator:
    network_mode: "host"
    build: .
    image: orchestrator:chainsight
    container_name: verity-chainsight-orchestrator
    environment:
      - ICP_URL=https://icp0.io
      - ADC_CANISTER=brbgg-kaaaa-aaaan-qmvzq-cai
      - ICP_IDENTITY_FILEPATH=./identity.pem
      - JOB_SCHEDULE=1/30 * * * * *
      - PROVER_URL=http://127.0.0.1:8080
      - PROVER_ZMQ_URL=tcp://127.0.0.1:5556
    # depends_on:
    #   - verity-prover