version: '3.8'
services:
  verity-prover:
    network_mode: "host"
    build:
      context: .prover
      dockerfile: prover.Dockerfile
    ports:
      - "8080:8080"
  
  orchestrator:
    network_mode: "host"
    build: .
    environment:
      - ICP_URL=https://icp0.io
      - ADC_CANISTER=brbgg-kaaaa-aaaan-qmvzq-cai
      - ICP_IDENTITY_FILEPATH=./identity.pem
      - JOB_SCHEDULE=1/30 * * * * *
      - PROVER_URL=http://0.0.0.0:8080
      - PROVER_ZMQ_URL=tcp://0.0.0.0:8000
    depends_on:
      - verity-prover