<<<<<<< HEAD
[workspace]
members = ["src/adc_caller", "src/adc_pulse"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
candid = "0.10"
clap = "4.5"
ic-agent = "0.39"
ic-cdk = "0.17"
rand = "0.8"
serde = "1.0"
tokio = "1.37"
tokio-cron-scheduler = "0.13"
tracing = "0.1"
tracing-subscriber = "0.3"
=======
[package]
name = "adc_caller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.16"
ic-cdk-timers = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
verity_dp_ic = { workspace = true }
>>>>>>> 686b766 (verify proof onchain)
