[package]
name = "types"
version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.93"
candid = "0.10.10"
serde = "1.0.215"
